
package sistemaventas;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class BuscarCliente extends javax.swing.JInternalFrame {

    
   conexion conectar=new conexion();
   Connection cn;
   CallableStatement cts;
   ResultSet r;
   
   ListSelectionModel lsClientes;

   
    public BuscarCliente() {
        initComponents();
        
        
        cn=conectar.conectado();
        cargar();
    }
    private void SelecionaCLiente(){
        int row=jTable1.getSelectedRow();
        String cod=jTable1.getValueAt(row, 0).toString();
        String nit=jTable1.getValueAt(row, 1).toString();
        String nom=jTable1.getValueAt(row, 2).toString();
        String dir=jTable1.getValueAt(row, 3).toString();
        
        Factura.lblCliente.setText(nom);
        Factura.lblNit.setText(nit);
        Factura.lblDireccion.setText(dir);
        
        this.dispose();
        //jTextField5.setText(id);
        
        
            
           // jTextField1.setText(Clientes.get(tb.getSelectedRows()).get);
        
    }
    
private void cargar(){
        
         DefaultTableModel tabla= new DefaultTableModel();
       try{
         tabla.addColumn("CODIGO");
         tabla.addColumn("NIT");
         tabla.addColumn("NOMBRES");
         tabla.addColumn("DIRECCION");
         
           
       cts=cn.prepareCall("{call MostrarCliente}");
       r=cts.executeQuery();
       while (r.next()){
       Object dato[]=new  Object[4];
       for (int i=0; i<4; i++){
           dato[i]=r.getString(i+1);

       }
       tabla.addRow(dato);
       }
       this.jTable1.setModel(tabla);
       }catch (Exception e){}}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIngreseNombre = new javax.swing.JTextField();
        btnBusqueda = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jMenuItem1.setText("Atualizar Registros");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exportar Registro");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Busqueda de clientes");

        jLabel2.setText("INGRESE NOMBRE:");

        txtIngreseNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIngreseNombreKeyReleased(evt);
            }
        });

        btnBusqueda.setText("BUSCAR");
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });

        btnRegistrar.setText("REGISTRAR CLIENTE");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIngreseNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBusqueda)
                        .addGap(27, 27, 27)
                        .addComponent(btnRegistrar)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(40, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBusqueda)
                        .addComponent(btnRegistrar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtIngreseNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
        // TODO add your handling code here:
        
        
        String nom=txtIngreseNombre.getText();
        DefaultTableModel tabla= new DefaultTableModel();
       try{
           
       tabla.addColumn("CODIGO");
       tabla.addColumn("NOMBRES");
       tabla.addColumn("DIRECCION");
       tabla.addColumn("TELEFONO");
              
         cts=cn.prepareCall("{call BuscarClienteFactura(?)}");
         cts.setString(1, nom);
         r=cts.executeQuery();
         
                 if (r.next())
                 {
                     Object dato[]=new  Object[4];
                     for (int i=0; i<4; i++)
                      {
                        dato[i]=r.getString(i+1);
                      }
                      
                 //    JOptionPane.showMessageDialog(this,"Cliente Encontrado!!","Aviso",JOptionPane.INFORMATION_MESSAGE);
              tabla.addRow(dato);
            /*         
            Factura.lblCodCliente.setText(r.getString(1));
            Factura.lblNit.setText(r.getString(2));
            Factura.lblCliente.setText(r.getString(3));
            Factura.lblDireccion.setText(r.getString(4));
            
                   this.dispose(); */
                     
                 }
                 
                 else{

           JOptionPane.showMessageDialog(this,"Cliente  No Encontrado!!","Aviso",JOptionPane.INFORMATION_MESSAGE);

            }
                 
                 
       this.jTable1.setModel(tabla);

       }catch (Exception e){}
    }//GEN-LAST:event_btnBusquedaActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        Clientes cli=new Clientes();
        SistemaV.jDesktopPane1.add(cli);
        cli.toFront();
        cli.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        cargar();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
       
        
        SelecionaCLiente();
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txtIngreseNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIngreseNombreKeyReleased
        // TODO add your handling code here:
        
        
        
        
        if(this.txtIngreseNombre.getText().isEmpty()){
       
        }
        else{
        try{
        String busq=this.txtIngreseNombre.getText();
        PreparedStatement psm=cn.prepareStatement("SELECT nombre FROM cliente WHERE nombre like '"+ busq +" %' ");
        ResultSet rs=psm.executeQuery();
        while(rs.next()){
        
        lsClientes.addListSelectionListener((ListSelectionListener) rs.getObject(1));
       
        }
        this.jTable1.setModel((TableModel) lsClientes);
        }catch(SQLException e){
        JOptionPane.showMessageDialog(null,"NO SE HA ENCONTRADO EL NOMBRE");
        }
        
        } 
        
    }//GEN-LAST:event_txtIngreseNombreKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusqueda;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtIngreseNombre;
    // End of variables declaration//GEN-END:variables
}
